# Here we show how to 

# 1 Download data from the PBDB database
  # 2 Clean occurrence data (including removal of uncertain taxonomical ranks, duplicates in bins, 
   # single-collection and single-reference taxa as well as missing higher-level taxonomy)
    # 3 Process data (bin data to stages, transform occurrence data to range data)
      # 4 Process istotope data for short-term temperature calculation 
        # 5 Calculate multiple long-term temperature trends based on taxonomical levels 
          # 5.1 Long-term trend based on genus level 
            # 5.2 Long-term trend based on family level  
              # 5.3 Long-term trend based on order level  
                # 6 Calculate multiple long-term temperature trends with varying length (1-10) based on stages 



# set working directory to where files are stored using the "rstudioapi" package

# Getting the path of this script
current_path = rstudioapi::getActiveDocumentContext()$path 

# setting it as working directory 
setwd(dirname(current_path ))

# please cross-check that this is the path where you store the other 
# files used for this script
getwd()


# loading packages 
library(paleobioDB)
library(rstudioapi)
library(tidyverse)
library(magrittr)
library(readr)
library(tidyr)
library(dplyr)
library(divDyn)




# 1 download data for Bivalvia from the PBDB database  --------------------


# download all bivalves occurrences from the paleobiology database.
# for other clades from the PBDB, 
# substitute "bivalvia" with one of the following in the pbdb_occurrences function: 
# arthropoda, gastropoda, reptilia, cnidaria, echinodermata 

# this might take some time, as it is quite a big file
# if this takes too long, you can directly download the cleaned data file at code line 150
bivalves_pbdb <-  pbdb_occurrences(limit="all",
                             base_name="bivalvia", vocab="pbdb",
                             show=c("coords", "phylo", "ident"))

# check the data set
head(bivalves_pbdb)

table(bivalves_pbdb$matched_rank)




# 2 clean occurrence data -------------------------------------------------


# remove subgenera
bivalves_pbdb <- subset(bivalves_pbdb, bivalves_pbdb$matched_rank != "subgenus")

# omit single-collection and single-reference taxa using the "omit" function from divdyn
toOmit <- omit(bivalves_pbdb, bin="stg", tax="genus", om="ref", ref="reference_no")
bivalves_pbdb <- bivalves_pbdb[!toOmit,]

# sometimes genus entries have brackets within the characters
# subset the genera with brackets and assign them to the overarching genus
bivalves_pbdb$genus <- gsub("\\s*\\([^\\)]+\\)","",as.character(bivalves_pbdb$genus))




# 3 process it (transform occurrence to range data, bin to stages)  -------


# using basic bin lengths to change it to range data using the "fadlad" function from divdyn
# to generate range data from an occurrence dataset
bivalves <- fadlad(bivalves_pbdb, tax="genus", age= c("early_age", "late_age"))

# assign genus names to a column
bivalves$genus <- rownames(bivalves)

# merge them together to get higher taxonomy
bivalves <- merge(bivalves,bivalves_pbdb, by  = "genus")

# order them properly
bivalves <- bivalves %>%
  select(phylum, class, order, family, genus, FAD, LAD)  

# remove the duplicates that were generated by merging
bivalves <- bivalves[!duplicated(bivalves),]

# remove the NA's
bivalves <- subset(bivalves, bivalves$class != "NO_CLASS_SPECIFIED" &
                     bivalves$order != "NO_ORDER_SPECIFIED" &
                     bivalves$family !=  "NO_FAMILY_SPECIFIED")

# check for NA's
bivalves <- na.omit(bivalves) # no NA's anymore, so good to go

# calculate durations
# bivalves$dur <- bivalves$FAD - bivalves$LAD
# mean(bivalves$dur) #61.29601
# median(bivalves$dur) #36.61

# import stage data from divdyn 
data(stages)

# as we have assigned the stage age from Gradstein 2012, we need to assign the same ages to the stage
# file
gradstein <- stages
rm(stages)

# these are the ages from Gradstein 2012
gradstein$bottom[c(21,50:55, 57:58, 71:74, 86:87, 90, 92, 95)] <- c(443.8, 259.8, 254.2, 252.2, 250.0,247.1, 241.5, 228.4, 209.5, 
                                                                    139.4, 133.9, 130.8, 126.3, 41.2, 37.8, 23.03, 11.63, 0.0118)
gradstein$top[21:length(gradstein$bottom)-1] <- gradstein$bottom[21:length(gradstein$bottom)]

# change colnames of our range data set
colnames(bivalves) <- c("Phylum", "Class", "Order", "Family", "Genus", "FAD.age", "LAD.age")


# bin FAD and LAD of each genus to stages  
bivalves$FAD_bin <- NA
bivalves$LAD_bin <- NA

for (i in 1:length(bivalves$Genus)) {
  for (j in 1:length(gradstein$stg)) {
    ifelse(gradstein$bottom[j] >= bivalves$FAD.age[i] & gradstein$top[j] < bivalves$FAD.age[i],
           bivalves$FAD_bin[i] <- gradstein$stg[j], NA)
    ifelse(gradstein$bottom[j] > bivalves$LAD.age[i] & gradstein$top[j] <= bivalves$LAD.age[i],
           bivalves$LAD_bin[i] <- gradstein$stg[j], NA)
  }}

#remove singletons as they add noise 
bivalves <- subset(bivalves, bivalves$FAD_bin != bivalves$LAD_bin)

# when genera range to the recent (bin 95), shift this bin to 94 to enable temperature-calculation
bivalves$LAD_bin[bivalves$LAD_bin==95] <- 94
bivalves <- subset(bivalves, bivalves$FAD_bin != bivalves$LAD_bin)

# subset to the same bins as we currently have for isotope data (isotemp) (>= 14)
bivalves <- subset(bivalves, bivalves$FAD_bin >=14)


# if downloading the data from scratches took to long, you can download the processed data file here:
# if you want to work with another clade, subset bivalvia at "bivalvia.csv" with on of the following clades:
# arthropoda, cnidaria, echinodermata, foraminifera, gastropoda, mammalia, reptilia

# bivalves <- read.table("bivalvia.csv", header = T)
# gradstein <- read.csv("gradstein.csv", header = T, row.names = 1)

# Cleanup
 rm(list=ls()[! ls() %in% c("bivalves", "gradstein")])



 
# 4 prepare istotope data for short-term temperature calculation ----------


# prepare weizer & prokoph temperature data. We are loading the file which was already processed as described
# in the methods paragraph and as described by Reddin et al. 2017
isotemp <- read.csv(file="TimeSeriesUsed.csv", header=TRUE,row.names = 1) 

# assign age to isotope data
isotemp$age <- gradstein$mid[14:94]

# take a look
ggplot(data=isotemp, aes(x=age, y=Temp))+
  geom_line(colour="grey50", size=1.5) + theme_classic()


# Calculate average Temperature per bin starting in the Ordovician (481.55 myr)

isotemp2<- isotemp %>%
  subset(age<=481.55000) %>%
  group_by(Stage) %>%
  summarise(Temp.mean = mean(Temp), n = n()) %>%
  arrange(desc(Stage))
isotemp2$age <- gradstein$mid[94:14]

# Add a column with short-term change (change.prev) in Temperature (temperature change from the previous to 
# the focal bin)
isotemp2$change.prev <- NA

# fill in the values for short-term change using the lm as we do for the long term trend as well
for (i in unique(isotemp$Stage)) {
  dum1 <- filter(isotemp, isotemp$Stage %in% isotemp$Stage[between(isotemp$Stage, i-1, i)])
  dum2 <-  lm(Temp ~ age, data = dum1)
  isotemp2[isotemp2$Stage==i, "change.prev"] <- -dum2$coefficients[2]
}

# Equal the number of temperature time bins 
isotemp2 %<>% subset(Stage>13 & Stage<95) %>%
  transform(bins = as.factor(Stage))  # We need bins as factor later on when binding with fossil data

rm(dum1, dum2, i)




# 5 Calculate multiple long-term temperature trends on taxonomical --------


# build dummies for calculation
dumbo <- bivalves
bivalves_safe <- bivalves[,c(5,8,9)]

# add bins with 0 and fill in with 1 for extinction and origination
namevector <- as.character(c(1:94))
bivalves_safe[ , namevector] <- NA
bivalves_safe <- bivalves_safe[, c(4:length(bivalves_safe[0,]))]

for (i in 1:length(bivalves_safe[,1])) {
  bivalves_safe[i,dumbo[i,8]] <- 0 
  bivalves_safe[i,dumbo[i,9]] <- 1
  ifelse(dumbo[i,8]!= dumbo[i,9]-1 & dumbo[i,8]!= dumbo[i,9],
         bivalves_safe[i,(dumbo[i,8]+1):(dumbo[i,9]-1)] <- 0, NA)
  ifelse(dumbo[i,9] == 94, bivalves_safe[i,dumbo[i,9]] <- 0, 
         bivalves_safe[i,dumbo[i,9]] <- 1)
}


# bind it again 
rownames(bivalves_safe) <-  make.names(dumbo[,5], unique=TRUE)


# Reorganise ranges through time data so we can bind it to temperature data
bivalves_safe %<>%  as_tibble() %>%
  mutate(Genus = rownames(bivalves_safe)) %>%
  group_by(Genus) %>%
  gather(-Genus, key="bins", value="extinct", na.rm = T, factor_key = T) %>%
  arrange(desc(bins), .by_group = T) 


# Now bind the two
temp_bivalves <- full_join(bivalves_safe, isotemp2)

#add taxonomical levels using the dummy
dumbo <- dumbo[, 2:5]

# Now bind the two
temp_bivalves <- full_join(temp_bivalves, dumbo)

# order it properly
temp_bivalves <- temp_bivalves %>%
  select(Class, Order, Family, Genus, bins, age, extinct, Temp.mean, change.prev) %>%
  transform(bins = as.numeric(as.character(bins))) %>%
  na.omit()




# 5.1 Long-term trend based on genus level ------------------------------------


# Calculate long term changes in temp (1 stage to 10 stages)
# Use lm() to determine slope of the long-term  temperature trends
# If we want to investigate the interaction between long term change and short term,
# we need to exclude the short term bin from the long term,
# and thus shift the long term lm result up by +1.

ori_bin <- temp_bivalves %>%
  select(Genus, bins, age) %>%
  group_by(Genus) %>%
  dplyr::slice(which.min(bins)) 
colnames(ori_bin) <- c("Genus", "ori.bin", "ori.age" )

# Now bind the two
temp_bivalves <- full_join(temp_bivalves, ori_bin)

# Set bins back to numeric and add columns for the trends
temp_bivalves %<>% transform(bins = as.numeric(as.character(bins)))
temp_bivalves$trend1 <- NA
temp_bivalves$trend2 <- NA
temp_bivalves$trend3 <- NA

# calculate the first trend starting using the lm at the origin of the focal genus and ending at one stage prior
# to the extinction to exlude short-term changefrom the long-term trend

for (i in 1:length(temp_bivalves$Genus)) {
  bin1 <- c(temp_bivalves$ori.bin[i], ifelse(temp_bivalves$bins[i]>temp_bivalves$ori.bin[i], 
                                             temp_bivalves$bins[i]-1, temp_bivalves$bins[i]))
  age1 <- c(isotemp$age[isotemp$Stage %in% bin1[1]:bin1[2]])
  
  temp1 <-c(isotemp$Temp[isotemp$Stage %in% bin1[1]:bin1[2]])
  lin1 <- lm(temp1~age1)
  temp_bivalves$trend1[i] <- -lin1$coefficients[2]
}


#remov ori age and bin to enable calculation of higher taxonomical trends
temp_bivalves <- temp_bivalves[,!(names(temp_bivalves) %in% c("ori.bin","ori.age"))]




# 5.2 Long-term trend based on family level -------------------------------


# now do the same for trend2, which starts at the origin of the family of the focal genus
# first build a data frame to save the origin of each family

biv_fam <- unique(bivalves$Family)
fam_dat <- data.frame(matrix(ncol =2 , nrow = length(biv_fam)))
colnames(fam_dat) <- c("age.ori", "bin.ori")
rownames(fam_dat) <-  c(as.character(biv_fam))

# now calculate the origin of each family
for (i in 1:length(fam_dat$age.ori)) {
  fam_dat[i, 2] <- min(bivalves$FAD_bin[bivalves$Family == biv_fam[i]])
  fam_dat[i, 1] <- isotemp$age[isotemp$Stage == fam_dat[i, 2]]
}

# add a colum with the family names for binding
fam_dat$Family <- rownames(fam_dat)

# Now bind the two
temp_bivalves <- full_join(temp_bivalves, fam_dat)

# now calculate the trend starting at origin of the focal family
for (i in 1:length(temp_bivalves$Genus)) {
  bin1 <- c(temp_bivalves$bin.ori[i], ifelse(temp_bivalves$bins[i]>temp_bivalves$bin.ori[i], 
                                             temp_bivalves$bins[i]-1, temp_bivalves$bins[i]))
  age1 <- c(isotemp$age[isotemp$Stage %in% bin1[1]:bin1[2]])
  
  temp1 <- c(isotemp$Temp[isotemp$Stage %in% bin1[1]:bin1[2]])
  lin1 <- lm(temp1~age1)
  temp_bivalves$trend2[i] <- -lin1$coefficients[2]
}

#remov ori age and bin
temp_bivalves <- temp_bivalves[,!(names(temp_bivalves) %in% c("bin.ori","age.ori"))]




# 5.3 Long-term trend based on order level --------------------------------


#now do the same for trend3, which starts at the origin of the order of the focal genus
# again, first build a data frame where we save the origin of each order

biv_ord <- unique(bivalves$Order)
ord_dat <- data.frame(matrix(ncol =2 , nrow = length(biv_ord)))
colnames(ord_dat) <- c("age.ori", "bin.ori")
rownames(ord_dat) <-  c(as.character(biv_ord))

# calculate the origin of each family
for (i in 1:length(ord_dat$age.ori)) {
  ord_dat[i, 2] <- min(bivalves$FAD_bin[bivalves$Order == biv_ord[i]])
  ord_dat[i, 1] <- isotemp$age[isotemp$Stage == ord_dat[i, 2]]
}

# add a colum with the superfamily names for binding
ord_dat$Order <- rownames(ord_dat)

# Now bind the two
temp_bivalves <- full_join(temp_bivalves, ord_dat)

# now calculate the trend starting at origin of the specific Order
for (i in 1:length(temp_bivalves$Genus)) {
  bin1 <- c(temp_bivalves$bin.ori[i], ifelse(temp_bivalves$bins[i]>temp_bivalves$bin.ori[i], 
                                             temp_bivalves$bins[i]-1, temp_bivalves$bins[i]))
  age1 <- c(isotemp$age[isotemp$Stage %in% bin1[1]:bin1[2]])
  temp1 <- c(isotemp$Temp[isotemp$Stage %in% bin1[1]:bin1[2]])
  lin1 <- lm(temp1~age1)
  temp_bivalves$trend3[i] <- -lin1$coefficients[2]
}


#remov ori age and bin
temp_bivalves <- temp_bivalves[,!(names(temp_bivalves) %in% c("bin.ori","age.ori"))]


# rename it 
three_trends_bivalves <- temp_bivalves


# Cleanup
rm(list=ls()[! ls() %in% c("isotemp", "isotemp2", "three_trends_bivalves")])




# 6 Calculate multiple long-term temperature trends with varying l --------


# Use lm() to determine slope of the long-termtemperature trends
# If we want to investigate the interaction between long term change and short term,
# we need to exclude the short term bin from the long term, and thus shift the long term lm result up by +1.

for (i in unique(isotemp$Stage)) {
  sub1<-filter(isotemp, isotemp$Stage %in% isotemp$Stage[between(isotemp$Stage, i-1, i)])
  lin1<-lm(Temp~age, data=sub1)
  isotemp2[isotemp2$Stage==i+1, "trend.st1"]<- -lin1$coefficients[2]
  sub2<-filter(isotemp, isotemp$Stage %in% isotemp$Stage[between(isotemp$Stage, i-2, i)])
  lin2<-lm(Temp~age, data=sub2)
  isotemp2[isotemp2$Stage==i+1, "trend.st2"]<- -lin2$coefficients[2]
  sub3<-filter(isotemp, isotemp$Stage %in% isotemp$Stage[between(isotemp$Stage, i-3, i)])
  lin3<-lm(Temp~age, data=sub3)
  isotemp2[isotemp2$Stage==i+1, "trend.st3"]<- -lin3$coefficients[2]
  sub4<-filter(isotemp, isotemp$Stage %in% isotemp$Stage[between(isotemp$Stage, i-4, i)])
  lin4<-lm(Temp~age, data=sub4)
  isotemp2[isotemp2$Stage==i+1, "trend.st4"]<- -lin4$coefficients[2]
  sub5<-filter(isotemp, isotemp$Stage %in% isotemp$Stage[between(isotemp$Stage, i-5, i)])
  lin5<-lm(Temp~age, data=sub5)
  isotemp2[isotemp2$Stage==i+1, "trend.st5"]<- -lin5$coefficients[2]
  sub6<-filter(isotemp, isotemp$Stage %in% isotemp$Stage[between(isotemp$Stage, i-6, i)])
  lin6<-lm(Temp~age, data=sub6)
  isotemp2[isotemp2$Stage==i+1, "trend.st6"]<- -lin6$coefficients[2]
  sub7<-filter(isotemp, isotemp$Stage %in% isotemp$Stage[between(isotemp$Stage, i-7, i)])
  lin7<-lm(Temp~age, data=sub7)
  isotemp2[isotemp2$Stage==i+1, "trend.st7"]<- -lin7$coefficients[2]
  sub8<-filter(isotemp, isotemp$Stage %in% isotemp$Stage[between(isotemp$Stage, i-8, i)])
  lin8<-lm(Temp~age, data=sub8)
  isotemp2[isotemp2$Stage==i+1, "trend.st8"]<- -lin8$coefficients[2]
  sub9<-filter(isotemp, isotemp$Stage %in% isotemp$Stage[between(isotemp$Stage, i-9, i)])
  lin9<-lm(Temp~age, data=sub9)
  isotemp2[isotemp2$Stage==i+1, "trend.st9"]<- -lin9$coefficients[2]
  sub10<-filter(isotemp, isotemp$Stage %in% isotemp$Stage[between(isotemp$Stage, i-10, i)])
  lin10<-lm(Temp~age, data=sub10)
  isotemp2[isotemp2$Stage==i+1, "trend.st10"]<- -lin10$coefficients[2]
}

# Cleanup
rm(i, isotemp, sub1, lin1, sub2, lin2, sub3, lin3, sub4, lin4, sub5, lin5, 
   sub6, lin6, sub7, lin7, sub8, lin8, sub9, lin9, sub10, lin10)

# Set bins back to factor for joining
three_trends_bivalves %<>% transform(bins = as.factor(as.character(bins)))

# Now bind the two
thirteen_trends_bivalves <- full_join(three_trends_bivalves, isotemp2)


# Set bins back to numeric
thirteen_trends_bivalves %<>% transform(bins = as.numeric(as.character(bins)))

# save it to your working directory
write.table(thirteen_trends_bivalves, file = "thirteen_trends_bivalves.csv")

